/**
 * Thème Art et lettres (series: 2)
 */
export default [
  {
    id: 'art-1',
    series: 2,
    text: 'Qui chante : « Fille des quartiers populaires, j’ai appris à en être fière… » ?',
    choices: ['Amel Bent', 'Diam’s', 'Sheryfa Luna', 'Jenifer'],
    answer: 0,
    explanation: 'Amel Bent, dans la chanson « Ma philosophie ».',
  },
  {
    id: 'art-2',
    series: 2,
    text: 'Dans quel film un homme noir des quartiers devient l’aide à domicile d’un homme blanc tétraplégique d’un milieu aisé ?',
    choices: ['Intouchables', 'Le Sens de la fête', 'Hors normes', 'Les Gamins'],
    answer: 0,
    explanation: 'Il s’agit du film « Intouchables ».',
  },
  {
    id: 'art-3',
    series: 2,
    text: 'Quel auteur-compositeur-interprète des quartiers populaires a eu les vertèbres atteintes suite à un accident de piscine ?',
    choices: ['Grand Corps Malade', 'Abd Al Malik', 'Disiz', 'Kery James'],
    answer: 0,
    explanation: 'Grand Corps Malade a été blessé lors d’un accident de piscine.',
  },
  {
    id: 'art-4',
    series: 2,
    text: 'Quel écrivain et homme d’État britannique était bègue ?',
    choices: ['Winston Churchill', 'Charles Dickens', 'Oscar Wilde', 'George Orwell'],
    answer: 0,
    explanation: 'Winston Churchill était bègue.',
  },
  {
    id: 'art-5',
    series: 2,
    text: 'Dans l’œuvre littéraire « L’Odyssée », Homère était-il sourd ou aveugle ?',
    choices: ['Sourd', 'Aveugle', 'Ni l’un ni l’autre', 'Les deux'],
    answer: 1,
    explanation: 'Homère était aveugle, selon la tradition ; il est le grand poète de l’histoire d’Ulysse.',
  },
  {
    id: 'art-6',
    series: 2,
    text: 'Quel rappeur caricatural des quartiers est co-fondateur du groupe NTM ?',
    choices: ['JoeyStarr', 'Booba', 'Rohff', 'La Fouine'],
    answer: 0,
    explanation: 'JoeyStarr est co-fondateur du groupe NTM.',
  },
  {
    id: 'art-7',
    series: 2,
    text: 'Quel footballeur français est originaire de Trappes ?',
    choices: ['Nicolas Anelka', 'Fabien Barthez', 'Djibril Cissé', 'Thierry Henry'],
    answer: 0,
    explanation: 'Nicolas Anelka est originaire de Trappes.',
  },
  {
    id: 'art-8',
    series: 2,
    text: 'Quelle chanson d’Yseult sortie en 2019 parle de l’acceptation de soi, de son physique et de sa couleur de peau ?',
    choices: ['Corps', 'Rien à prouver', 'Menticide', 'Évidemment'],
    answer: 0,
    explanation: '« Corps » — Yseult a aussi remporté la Victoire de la révélation féminine.',
  },
  {
    id: 'art-9',
    series: 2,
    text: 'Quel film illustre la difficulté à vivre avec la surdité et la problématique de l’émancipation lorsqu’on est aidant d’un proche ?',
    choices: ['La Famille Bélier', 'Marie Heurtin', 'Le Scaphandre et le Papillon', 'Amour'],
    answer: 0,
    explanation: '« La Famille Bélier ».',
  },
  {
    id: 'art-10',
    series: 2,
    text: 'Quelle comédie française, réalisée par Artus, explore les préjugés autour du handicap mental avec humour ?',
    choices: ['Un p’tit truc en plus', 'Le Premier Jour du reste de ta vie', 'Intouchables', 'Les Choristes'],
    answer: 0,
    explanation: '« Un p’tit truc en plus », réalisé par Artus.',
  },
  {
    id: 'art-11',
    series: 2,
    text: 'Quel humoriste français, issu des quartiers et en situation de handicap, a tenu le rôle de Numérobis dans Astérix & Obélix : Mission Cléopâtre ?',
    choices: ['Jamel Debbouze', 'Gad Elmaleh', 'Omar Sy', 'Éric Judor'],
    answer: 0,
    explanation: 'Jamel Debbouze incarne Numérobis.',
  },
  {
    id: 'art-12',
    series: 2,
    text: 'Quelle comédie de 2008 réalisée par Gabriel Julien-Laferrière aborde la banlieue, le choc culturel et le racisme latent ?',
    choices: ['Neuilly sa mère !', 'Les Kaïra', 'Banlieue 13', 'Divines'],
    answer: 0,
    explanation: '« Neuilly sa mère ! ».',
  },
  {
    id: 'art-13',
    series: 2,
    text: 'Quel film culte sur la banlieue française, tourné en noir et blanc, illustre la violence policière et la jeunesse en colère dans les années 90 ?',
    choices: ['La Haine', 'Ma 6-T va crack-er', 'L’Esquive', 'Entre les murs'],
    answer: 0,
    explanation: '« La Haine », de Mathieu Kassovitz.',
  },
  {
    id: 'art-14',
    series: 2,
    text: 'Quelle personnalité du divertissement français a écrit : « Dois-je me justifier d’être Noir, d’être dyslexique, d’être gros… » ?',
    choices: ['Issa Doumbia', 'Jamel Debbouze', 'Omar Sy', 'Ramzy Bedia'],
    answer: 0,
    explanation: 'Issa Doumbia.',
  },
  {
    id: 'art-15',
    series: 2,
    text: 'Quel titre d’Angèle est une critique des comportements misogynes mis en lumière par le mouvement « Me Too » ?',
    choices: ['Balance ton quoi', 'Tout oublier', 'Libre', 'Bruxelles je t’aime'],
    answer: 0,
    explanation: '« Balance ton quoi ».',
  },
  {
    id: 'art-16',
    series: 2,
    text: 'Quel groupe français des quartiers a chanté : « Tous les enfants de ma cité et même d’ailleurs… » ?',
    choices: ['Zebda', 'IAM', 'Suprême NTM', 'Assassin'],
    answer: 0,
    explanation: 'Zebda, dans « Tombez la chemise ».',
  },
];
