/**
 * Thème Préjugé (series: 1)
 */
export default [
  {
    id: 'prejuge-1',
    series: 1,
    text: 'Quel est, en France, le 1er critère de discrimination au recrutement ?',
    choices: ['L’âge', 'Le sexe', 'Les convictions religieuses', 'Le lieu de résidence'],
    answer: 0,
    explanation: 'L’âge est le premier critère de discrimination au recrutement, confirmé par les entreprises et cabinets de recrutement.',
  },
  {
    id: 'prejuge-2',
    series: 1,
    text: 'Quel est le pays où la discrimination est la plus faible ?',
    choices: ['La Belgique', 'Le Danemark', 'L’Australie', 'La France'],
    answer: 1,
    explanation: 'Le Danemark apparaît parmi les pays où la discrimination est la plus faible.',
  },
  {
    id: 'prejuge-3',
    series: 1,
    text: 'Quelle est la meilleure définition du stéréotype ?',
    choices: [
      'C’est la vérité sur les autres',
      'Ce que définit une personne',
      'Une image toute faite dans notre tête, qui fait ignorer la différence',
      'Une opinion fondée sur des faits vérifiés',
    ],
    answer: 2,
    explanation: 'Un stéréotype est une image toute faite qui simplifie et ignore les différences individuelles.',
  },
  {
    id: 'prejuge-4',
    series: 1,
    text: 'Quel animal dit « méchant » a mis en évidence l’impact des préjugés lors d’une publicité de Noël ?',
    choices: ['Le tigre', 'Le loup', 'L’ours', 'Le renard'],
    answer: 1,
    explanation: 'C’est le loup, dans une publicité qui joue sur les préjugés.',
  },
  {
    id: 'prejuge-5',
    series: 1,
    text: 'Selon le stéréotype, la femme est plus…',
    choices: ['Faible', 'Courageuse', 'Forte', 'Indépendante'],
    answer: 0,
    explanation: 'Le stéréotype classique présente la femme comme « plus faible ».',
  },
  {
    id: 'prejuge-6',
    series: 1,
    text: 'Quel homme, symbole de paix, a été condamné pour sa lutte contre la ségrégation raciale ?',
    choices: ['Martin Luther King', 'Nelson Mandela', 'Gandhi', 'Desmond Tutu'],
    answer: 1,
    explanation: 'Nelson Mandela a été condamné et emprisonné pour sa lutte contre l’apartheid.',
  },
  {
    id: 'prejuge-7',
    series: 1,
    text: 'En France, quel corps d’armée est le plus féminisé ?',
    choices: [
      'L’armée de l’Air et de l’Espace',
      'L’armée de Terre',
      'La Marine nationale',
      'La Gendarmerie',
    ],
    answer: 0,
    explanation: 'Avec environ 23 % de femmes dans ses effectifs, c’est l’armée de l’Air et de l’Espace.',
  },
  {
    id: 'prejuge-8',
    series: 1,
    text: 'C’est illégal d’être réfugié.',
    choices: ['Vrai', 'Faux', 'Uniquement hors Europe', 'Uniquement sans papiers'],
    answer: 1,
    explanation: 'Faux : « réfugié » est un statut légal pour les personnes qui fuient les conflits ou la persécution.',
  },
  {
    id: 'prejuge-9',
    series: 1,
    text: 'Les personnes faibles de caractère ou de nature paresseuse sont plus à risque de développer une maladie mentale.',
    choices: ['Vrai', 'Faux', 'Uniquement chez les adolescents', 'Uniquement au travail'],
    answer: 1,
    explanation: 'Faux : c’est un préjugé. La maladie mentale n’est pas liée à la « faiblesse de caractère ».',
  },
  {
    id: 'prejuge-10',
    series: 1,
    text: 'Dans quelle profession manque-t-on le plus d’hommes ?',
    choices: ['Magistrat', 'Ingénieur', 'Expert-comptable', 'Informaticien'],
    answer: 0,
    explanation: 'Chez les magistrats, seulement environ 29 % sont des hommes.',
  },
  {
    id: 'prejuge-11',
    series: 1,
    text: 'Quel est le point commun entre le télescope submersible, le langage de programmation et le 1er programme informatique ?',
    choices: [
      'Ils ont été créés à la même période',
      'Ils ont été créés par des femmes',
      'Ils ont été testés par des enfants',
      'Ils viennent des États-Unis',
    ],
    answer: 1,
    explanation: 'Ils ont été créés par des femmes — un fait souvent effacé par les stéréotypes.',
  },
  {
    id: 'prejuge-12',
    series: 1,
    text: 'La majorité des crimes « violents » sont commis par des gens ayant un problème de santé mentale.',
    choices: ['Vrai', 'Faux', 'Environ la moitié', 'Uniquement les crimes graves'],
    answer: 1,
    explanation: 'Faux : environ 97 % des crimes sont commis par des personnes sans problème de santé mentale.',
  },
  {
    id: 'prejuge-13',
    series: 1,
    text: 'Les stéréotypes sont des idées ou croyances. Les préjugés sont des attitudes. La discrimination est un comportement.',
    choices: ['Vrai', 'Faux', 'C’est l’inverse', 'Ce sont des synonymes'],
    answer: 0,
    explanation: 'Vrai : et l’un renforce souvent l’autre.',
  },
  {
    id: 'prejuge-14',
    series: 1,
    text: 'Les femmes sont sous-représentées à la télévision et à la radio. Quelle proportion des personnes à l’antenne représentent-elles ?',
    choices: ['2 %', '10 %', '38 %', '50 %'],
    answer: 2,
    explanation: 'Les femmes représentent environ 38 % des personnes à l’antenne.',
  },
  {
    id: 'prejuge-15',
    series: 1,
    text: 'Quel est le pourcentage de personnes grosses qui subissent de la grossophobie au travail ?',
    choices: ['5 %', '17 %', '54 %', '30 %'],
    answer: 2,
    explanation:
      '54 % des personnes grosses, hommes ou femmes, déclarent subir de la grossophobie sur leur lieu de travail.',
  },
];
