/**
 * Thème Santé (series: 0)
 * — id unique, answer = index 0-3 de la bonne réponse
 */
export default [
  {
    id: 'sante-1',
    series: 0,
    text: 'Quel est le pourcentage des handicaps invisibles reconnus en France ?',
    choices: ['60 %', '80 %', '40 %', '25 %'],
    answer: 1,
    explanation: 'Environ 80 % des handicaps reconnus sont invisibles (cancer, diabète, troubles dys…).',
  },
  {
    id: 'sante-2',
    series: 0,
    text: 'Comment se nomme la discrimination contre les personnes handicapées ?',
    choices: ['Le capacitisme', 'Le potentialisme', 'L’aptitudialisme', 'Le validisme social'],
    answer: 0,
    explanation: 'On parle de capacitisme (parfois aussi d’incapacitisme) : discrimination fondée sur le handicap.',
  },
  {
    id: 'sante-3',
    series: 0,
    text: 'Quelle personnalité est devenue l’ambassadeur de la mucoviscidose ?',
    choices: ['Christophe Willem', 'Grégory Lemarchal', 'Cyril Mosimann', 'Pascal Obispo'],
    answer: 1,
    explanation: 'Grégory Lemarchal est devenu un ambassadeur emblématique de la lutte contre la mucoviscidose.',
  },
  {
    id: 'sante-4',
    series: 0,
    text: 'Toutes les personnes atteintes du syndrome de Gilles de la Tourette profèrent des injures à tout moment.',
    choices: ['Vrai', 'Faux', 'Uniquement chez l’adulte', 'Uniquement en public'],
    answer: 1,
    explanation: 'Faux : seul un petit pourcentage des personnes concernées présente cette forme de symptômes.',
  },
  {
    id: 'sante-5',
    series: 0,
    text: 'Au départ, le VIH a été transmis à l’Homme par l’homme.',
    choices: ['Vrai', 'Faux', 'Par les oiseaux', 'Par l’eau contaminée uniquement'],
    answer: 1,
    explanation: 'Faux : le virus a été transmis à l’humain à partir de singes (zoonose).',
  },
  {
    id: 'sante-6',
    series: 0,
    text: 'Quelle est la proportion des personnes qui deviennent handicapées au cours de la vie ?',
    choices: ['50 %', '70 %', '85 %', '30 %'],
    answer: 2,
    explanation: 'Environ 85 % des situations de handicap apparaissent au cours de la vie (et non à la naissance).',
  },
  {
    id: 'sante-7',
    series: 0,
    text: 'La maladie mentale et la déficience intellectuelle sont liées.',
    choices: ['Vrai', 'Faux', 'Toujours', 'Uniquement chez l’enfant'],
    answer: 1,
    explanation: 'Faux : la maladie mentale relève du domaine psychique ; ce n’est pas la même chose qu’une déficience intellectuelle.',
  },
  {
    id: 'sante-8',
    series: 0,
    text: 'La maladie mentale est la principale cause d’absentéisme au travail.',
    choices: ['Vrai', 'Faux', 'Uniquement dans le privé', 'Uniquement après 50 ans'],
    answer: 0,
    explanation: 'Vrai : elle est responsable d’environ 35 à 45 % de l’absentéisme au travail.',
  },
  {
    id: 'sante-9',
    series: 0,
    text: 'Près d’une personne sur 5 souffrira d’une maladie mentale au cours de sa vie.',
    choices: ['Vrai', 'Faux', 'Une personne sur 10', 'Une personne sur 2'],
    answer: 1,
    explanation: 'Faux : c’est plutôt une personne sur 4 qui souffrira d’un trouble mental à un moment de sa vie.',
  },
  {
    id: 'sante-10',
    series: 0,
    text: 'Combien existe-t-il de catégories de handicap ?',
    choices: [
      '2 : visibles et invisibles',
      '7 : physiques, sensoriels, mentaux, cognitifs, psychiques, polyhandicaps, troubles invalidants',
      '4 : surdité, déficience visuelle, autisme, troubles de la mobilité',
      '3 : moteur, sensoriel, psychique',
    ],
    answer: 1,
    explanation: 'Il existe 7 grandes catégories de handicap.',
  },
  {
    id: 'sante-11',
    series: 0,
    text: 'Quel est le taux de chômage des personnes handicapées en France ?',
    choices: ['16 %', '18 %', '22 %', '10 %'],
    answer: 1,
    explanation: 'Le taux de chômage des personnes handicapées est d’environ 18 %.',
  },
  {
    id: 'sante-12',
    series: 0,
    text: 'Qui ne participe pas au financement de la Sécurité sociale ?',
    choices: [
      'Les mutuelles',
      'Les cotisations sociales payées par les employeurs',
      'La CSG (contribution sociale généralisée)',
      'Les salariés via leurs cotisations',
    ],
    answer: 0,
    explanation: 'Les mutuelles ne financent pas la Sécurité sociale : ce sont des complémentaires santé.',
  },
  {
    id: 'sante-13',
    series: 0,
    text: 'Que signifie RQTH ?',
    choices: [
      'Réservé qualification travailleur handicapé',
      'Reconnaissance de la qualité de travailleur handicapé',
      'Reconnu et qualifié travailleur handicapé',
      'Régime quotité travailleur handicapé',
    ],
    answer: 1,
    explanation: 'RQTH = Reconnaissance de la qualité de travailleur handicapé.',
  },
  {
    id: 'sante-14',
    series: 0,
    text: 'Quelle est l’origine du mot « handicap » ?',
    choices: [
      'Du professeur Andy Kapp, psychiatre',
      'D’un jeu de troc anglais',
      'Des blessés de guerre au Moyen Âge',
      'D’un terme médical latin',
    ],
    answer: 1,
    explanation: 'Le mot vient d’un jeu de troc anglais (« hand in cap »).',
  },
  {
    id: 'sante-15',
    series: 0,
    text: 'Parmi ces organismes, lequel ne fait pas partie de la Sécurité sociale ?',
    choices: ['L’Assurance retraite', 'France Travail', 'Le Conseil départemental', 'L’Assurance maladie'],
    answer: 2,
    explanation: 'Le Conseil départemental n’est pas un organisme de la Sécurité sociale.',
  },
  {
    id: 'sante-16',
    series: 0,
    text: 'Qui peut bénéficier du 100 % Santé ?',
    choices: [
      'Uniquement les bénéficiaires de la CSS',
      'Tous les Français avec une complémentaire santé responsable ou la CSS',
      'Uniquement les retraités',
      'Uniquement les personnes RQTH',
    ],
    answer: 1,
    explanation:
      'Depuis le 1er janvier 2021, l’offre 100 % Santé concerne tous les Français bénéficiant d’une complémentaire santé responsable ou de la Complémentaire santé solidaire.',
  },
  {
    id: 'sante-17',
    series: 0,
    text: 'La mention « poste réservé aux personnes en situation de handicap » peut être utilisée dans les offres d’emploi.',
    choices: ['Vrai', 'Faux', 'Uniquement dans le public', 'Uniquement via France Travail'],
    answer: 1,
    explanation:
      'Faux : vous ne pouvez pas écarter les candidatures de personnes sans handicap de cette façon.',
  },
];
